"""
Script para crear las tablas de pagina ejecutando el SQL directamente
"""
import os
from dotenv import load_dotenv
from django.conf import settings

load_dotenv()
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proyecto.settings')

import django
django.setup()

from django.db import connection

# SQL de la migración
sql = """
BEGIN;
CREATE TABLE IF NOT EXISTS "usuarios" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "nombre_completo" varchar(200) NOT NULL, "rol" varchar(20) NOT NULL, "activo" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "usuarios_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "parametros" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "clave" varchar(100) NOT NULL UNIQUE, "valor" text NOT NULL, "descripcion" text NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "rutas" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "codigo" varchar(50) NOT NULL UNIQUE, "nombre" varchar(200) NOT NULL, "descripcion" text NULL, "activa" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "usuario_rutas" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "ruta_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "notas_credito" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "serie_folio" varchar(100) NOT NULL UNIQUE, "fecha_nota" date NOT NULL, "cliente" varchar(200) NOT NULL, "monto" numeric(12, 2) NOT NULL, "abono" numeric(12, 2) NOT NULL, "saldo" numeric(12, 2) NOT NULL, "estado" varchar(20) NOT NULL, "resuelta_automaticamente" boolean NOT NULL, "fecha_creacion" date NOT NULL, "fecha_ultima_actualizacion" timestamp with time zone NOT NULL, "fecha_resolucion" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "ruta_id" bigint NOT NULL, "usuario_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "importaciones" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre_archivo" varchar(255) NOT NULL, "total_registros" integer NOT NULL, "registros_nuevos" integer NOT NULL, "registros_actualizados" integer NOT NULL, "registros_resueltos" integer NOT NULL, "estado" varchar(20) NOT NULL, "observaciones" text NULL, "created_at" timestamp with time zone NOT NULL, "usuario_id" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "historial_notas" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "campo_modificado" varchar(100) NOT NULL, "valor_anterior" text NULL, "valor_nuevo" text NULL, "observacion" text NULL, "created_at" timestamp with time zone NOT NULL, "nota_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "documentos" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre_archivo" varchar(255) NOT NULL, "ruta_archivo" varchar(500) NOT NULL, "tipo_mime" varchar(100) NULL, "tamanio" integer NULL, "created_at" timestamp with time zone NOT NULL, "nota_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "alertas" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "tipo" varchar(20) NOT NULL, "descripcion" text NOT NULL, "leida" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "nota_id" bigint NOT NULL, "usuario_asignado_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "aclaraciones" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "comentario" text NOT NULL, "tipo" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "nota_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);
CREATE TABLE IF NOT EXISTS "usuarios_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);
COMMIT;
"""

# Ejecutar SQL
cursor = connection.cursor()

try:
    # Ejecutar cada comando por separado
    commands = sql.split(';')
    for cmd in commands:
        cmd = cmd.strip()
        if cmd and not cmd.startswith('--') and cmd.upper() not in ['BEGIN', 'COMMIT']:
            try:
                cursor.execute(cmd)
                print(f'[OK] Ejecutado: {cmd[:50]}...')
            except Exception as e:
                if 'already exists' not in str(e).lower() and 'duplicate' not in str(e).lower():
                    print(f'[INFO] {e}')
    
    connection.commit()
    print('\n[OK] Tablas creadas')
    
    # Crear índices y constraints
    print('\nCreando indices y constraints...')
    indices_sql = """
    CREATE INDEX IF NOT EXISTS "usuario_rut_usuario_4291a9_idx" ON "usuario_rutas" ("usuario_id", "ruta_id");
    ALTER TABLE "usuario_rutas" ADD CONSTRAINT IF NOT EXISTS "usuario_rutas_usuario_id_ruta_id_60f54d57_uniq" UNIQUE ("usuario_id", "ruta_id");
    CREATE INDEX IF NOT EXISTS "idx_notas_serie_folio" ON "notas_credito" ("serie_folio");
    CREATE INDEX IF NOT EXISTS "idx_notas_ruta" ON "notas_credito" ("ruta_id");
    CREATE INDEX IF NOT EXISTS "idx_notas_usuario" ON "notas_credito" ("usuario_id");
    CREATE INDEX IF NOT EXISTS "idx_notas_estado" ON "notas_credito" ("estado");
    CREATE INDEX IF NOT EXISTS "idx_notas_fecha" ON "notas_credito" ("fecha_nota");
    CREATE INDEX IF NOT EXISTS "idx_historial_nota" ON "historial_notas" ("nota_id");
    CREATE INDEX IF NOT EXISTS "idx_alertas_leida" ON "alertas" ("leida");
    CREATE INDEX IF NOT EXISTS "idx_aclaraciones_nota" ON "aclaraciones" ("nota_id");
    """
    
    for cmd in indices_sql.split(';'):
        cmd = cmd.strip()
        if cmd:
            try:
                cursor.execute(cmd)
            except Exception as e:
                if 'already exists' not in str(e).lower():
                    print(f'[INFO] {e}')
    
    connection.commit()
    print('[OK] Indices creados')
    
except Exception as e:
    connection.rollback()
    print(f'[ERROR] {e}')
finally:
    cursor.close()

print('\n[OK] Proceso completado')




