# Generated by Django 4.2.27 on 2026-01-22 20:30

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('rol', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('CREDITO', 'Crédito y Cobranza'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'db_table': 'parametros',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ruta', models.ForeignKey(db_column='ruta_id', on_delete=django.db.models.deletion.CASCADE, to='pagina.ruta')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Ruta',
                'verbose_name_plural': 'Usuarios-Rutas',
                'db_table': 'usuario_rutas',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_folio', models.CharField(max_length=100, unique=True, verbose_name='Serie-Folio')),
                ('fecha_nota', models.DateField(verbose_name='Fecha de la Nota')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('abono', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Abono')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ACLARADA', 'Aclarada'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('resuelta_automaticamente', models.BooleanField(default=False, verbose_name='Resuelta Automáticamente')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ruta', models.ForeignKey(db_column='ruta_id', on_delete=django.db.models.deletion.PROTECT, to='pagina.ruta', verbose_name='Ruta')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'notas_credito',
                'ordering': ['-fecha_nota', 'serie_folio'],
            },
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('total_registros', models.IntegerField(verbose_name='Total de Registros')),
                ('registros_nuevos', models.IntegerField(default=0, verbose_name='Registros Nuevos')),
                ('registros_actualizados', models.IntegerField(default=0, verbose_name='Registros Actualizados')),
                ('registros_resueltos', models.IntegerField(default=0, verbose_name='Registros Resueltos')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('PARCIAL', 'Parcial')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'db_table': 'importaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('nota', models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pagina.notacredito', verbose_name='Nota de Crédito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Nota',
                'verbose_name_plural': 'Historial de Notas',
                'db_table': 'historial_notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('tamanio', models.IntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('nota', models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pagina.notacredito', verbose_name='Nota de Crédito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REAPARICION', 'Reaparición'), ('ANTIGUA', 'Antigua'), ('DISCREPANCIA', 'Discrepancia'), ('CAMBIO_RUTA', 'Cambio de Ruta')], max_length=20, verbose_name='Tipo de Alerta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('nota', models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pagina.notacredito', verbose_name='Nota de Crédito')),
                ('usuario_asignado', models.ForeignKey(blank=True, db_column='usuario_asignado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-created_at', 'leida'],
            },
        ),
        migrations.CreateModel(
            name='Aclaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('ACLARACION', 'Aclaración'), ('SEGUIMIENTO', 'Seguimiento')], default='COMENTARIO', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('nota', models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, related_name='aclaraciones', to='pagina.notacredito', verbose_name='Nota de Crédito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Aclaración',
                'verbose_name_plural': 'Aclaraciones',
                'db_table': 'aclaraciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rutas',
            field=models.ManyToManyField(related_name='usuarios', through='pagina.UsuarioRuta', to='pagina.ruta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='usuarioruta',
            index=models.Index(fields=['usuario', 'ruta'], name='usuario_rut_usuario_4291a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioruta',
            unique_together={('usuario', 'ruta')},
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['serie_folio'], name='idx_notas_serie_folio'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['ruta'], name='idx_notas_ruta'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['usuario'], name='idx_notas_usuario'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['estado'], name='idx_notas_estado'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['fecha_nota'], name='idx_notas_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialnota',
            index=models.Index(fields=['nota'], name='idx_historial_nota'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['leida'], name='idx_alertas_leida'),
        ),
        migrations.AddIndex(
            model_name='aclaracion',
            index=models.Index(fields=['nota'], name='idx_aclaraciones_nota'),
        ),
    ]
