# Generated by Django 4.2.27 on 2026-01-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa'),
        ),
    ]
