# Generated by Django 4.2.27 on 2026-01-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_notacredito_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='serie_folio',
            field=models.CharField(max_length=100, verbose_name='Serie-Folio'),
        ),
        migrations.AlterUniqueTogether(
            name='notacredito',
            unique_together={('empresa', 'serie_folio')},
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['empresa', 'serie_folio'], name='idx_notas_empresa_serie'),
        ),
    ]
