# Generated by Django 4.2.27 on 2026-01-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_notacredito_serie_folio_and_more'),
    ]

    operations = [
        # Primero actualizar valores null a 'DISTRIBUIDORA'
        migrations.RunSQL(
            "UPDATE notas_credito SET empresa = 'DISTRIBUIDORA' WHERE empresa IS NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='empresa',
            field=models.CharField(choices=[('DISTRIBUIDORA', 'Distribuidora'), ('RODRIGO', 'Rodrigo')], default='DISTRIBUIDORA', help_text='Solo puede ser DISTRIBUIDORA o RODRIGO', max_length=200, verbose_name='Empresa'),
        ),
        # Agregar constraint CHECK en la base de datos
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'check_empresa_valida'
                ) THEN
                    ALTER TABLE notas_credito 
                    ADD CONSTRAINT check_empresa_valida 
                    CHECK (empresa IN ('DISTRIBUIDORA', 'RODRIGO'));
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE notas_credito DROP CONSTRAINT IF EXISTS check_empresa_valida;"
        ),
    ]
