# Generated by Django 4.2.27 on 2026-01-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_add_empresa_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='usuario_vendedor_pv',
            field=models.CharField(blank=True, help_text='Valor interno del punto de venta (ej: PERSONA_1, PERSONA_2). No tiene relación con usuario_id.', max_length=200, null=True, verbose_name='Usuario/Vendedor (Punto de Venta)'),
        ),
    ]
