# Generated by Django 4.2.27 on 2026-01-26 16:38

from django.db import migrations, models


def convertir_estados_antiguos(apps, schema_editor):
    """
    Convierte los estados EN_PROCESO y ACLARADA a PENDIENTE
    antes de actualizar las opciones del campo
    """
    NotaCredito = apps.get_model('pagina', 'NotaCredito')
    
    # Convertir EN_PROCESO a PENDIENTE
    NotaCredito.objects.filter(estado='EN_PROCESO').update(estado='PENDIENTE')
    
    # Convertir ACLARADA a PENDIENTE
    NotaCredito.objects.filter(estado='ACLARADA').update(estado='PENDIENTE')


def revertir_estados(apps, schema_editor):
    """
    Función de reversión (no hace nada ya que no podemos saber
    qué notas eran EN_PROCESO y cuáles ACLARADA)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_rename_fecha_creacion_to_fecha_corriente'),
    ]

    operations = [
        # Primero convertir los datos existentes
        migrations.RunPython(convertir_estados_antiguos, revertir_estados),
        # Luego actualizar el campo con las nuevas opciones
        migrations.AlterField(
            model_name='notacredito',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_corriente',
            field=models.DateField(verbose_name='Fecha Corriente'),
        ),
    ]
