# Generated by Django 4.2.27 on 2026-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_simplificar_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclaracion',
            name='leida',
            field=models.BooleanField(default=False, help_text='Indica si el comentario ha sido visto por crédito/cobranza', verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('REAPARICION', 'Reaparición'), ('ANTIGUA', 'Antigua'), ('DISCREPANCIA', 'Discrepancia'), ('CAMBIO_RUTA', 'Cambio de Ruta'), ('NUEVO_COMENTARIO', 'Nuevo Comentario')], max_length=20, verbose_name='Tipo de Alerta'),
        ),
    ]
