# Generated by Django 4.2.27 on 2026-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_agregar_leida_aclaracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='requiere_atencion',
            field=models.BooleanField(default=False, help_text='Indica si la nota tiene comentarios o información pendiente de revisar', verbose_name='Requiere Atención'),
        ),
    ]
